//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheHouse.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TheHouseEntities : DbContext
    {
        public TheHouseEntities()
            : base("name=TheHouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Category> tbl_Category { get; set; }
        public virtual DbSet<tbl_Guest> tbl_Guest { get; set; }
        public virtual DbSet<tbl_House> tbl_House { get; set; }
        public virtual DbSet<tbl_RoomsDetails> tbl_RoomsDetails { get; set; }
        public virtual DbSet<tbl_Type> tbl_Type { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<tbl_RoomCharges> tbl_RoomCharges { get; set; }
        public virtual DbSet<tbl_BookingBridge> tbl_BookingBridge { get; set; }
        public virtual DbSet<tbl_Booking> tbl_Booking { get; set; }
        public virtual DbSet<tbl_Payment> tbl_Payment { get; set; }
        public virtual DbSet<tbl_CardDetails> tbl_CardDetails { get; set; }
    
        public virtual ObjectResult<sp_RoomCategoryByUserId_Result> sp_RoomCategoryByUserId(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RoomCategoryByUserId_Result>("sp_RoomCategoryByUserId", userIdParameter);
        }
    
        public virtual ObjectResult<sp_RoomDetails_Result> sp_RoomDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RoomDetails_Result>("sp_RoomDetails");
        }
    
        public virtual ObjectResult<sp_SelectHouseDetailById_Result> sp_SelectHouseDetailById(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SelectHouseDetailById_Result>("sp_SelectHouseDetailById", userIdParameter);
        }
    
        public virtual ObjectResult<sp_SelectUserDetailById_Result> sp_SelectUserDetailById(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SelectUserDetailById_Result>("sp_SelectUserDetailById", userIdParameter);
        }
    }
}
