//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Category()
        {
            this.tbl_RoomsDetails = new HashSet<tbl_RoomsDetails>();
            this.tbl_Type = new HashSet<tbl_Type>();
            this.tbl_RoomCharges = new HashSet<tbl_RoomCharges>();
        }
    
        public int Cat_Id { get; set; }
        public Nullable<int> FK_HouseID { get; set; }
        public string Cat_Name { get; set; }
        public string Cat_Description { get; set; }
        public Nullable<bool> Cat_Status { get; set; }
    
        public virtual tbl_House tbl_House { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RoomsDetails> tbl_RoomsDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Type> tbl_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RoomCharges> tbl_RoomCharges { get; set; }
    }
}
