//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_User()
        {
            this.tbl_House = new HashSet<tbl_House>();
        }
    
        public int User_Id { get; set; }
        public string FullName { get; set; }
        public string UserEmail { get; set; }
        public string UserPass { get; set; }
        public string UserContact { get; set; }
        public string UserAddress { get; set; }
        public string UserImage { get; set; }
        public string CreatedDate { get; set; }
        public string UserType { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_House> tbl_House { get; set; }
    }
}
