//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Type()
        {
            this.tbl_RoomCharges = new HashSet<tbl_RoomCharges>();
            this.tbl_RoomsDetails = new HashSet<tbl_RoomsDetails>();
        }
    
        public int Type_Id { get; set; }
        public Nullable<int> FK_CateID { get; set; }
        public string Type_Name { get; set; }
        public string Type_Description { get; set; }
        public Nullable<bool> Type_Status { get; set; }
    
        public virtual tbl_Category tbl_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RoomCharges> tbl_RoomCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RoomsDetails> tbl_RoomsDetails { get; set; }
    }
}
