//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BookingBridge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_BookingBridge()
        {
            this.tbl_Payment = new HashSet<tbl_Payment>();
        }
    
        public int BB_ID { get; set; }
        public Nullable<int> FK_BookingID { get; set; }
        public Nullable<int> FK_HouseID { get; set; }
        public Nullable<int> FK_RoomID { get; set; }
        public Nullable<int> FK_GuestID { get; set; }
    
        public virtual tbl_Booking tbl_Booking { get; set; }
        public virtual tbl_Guest tbl_Guest { get; set; }
        public virtual tbl_House tbl_House { get; set; }
        public virtual tbl_RoomsDetails tbl_RoomsDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Payment> tbl_Payment { get; set; }
    }
}
