//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RoomCharges
    {
        public int RC_Id { get; set; }
        public Nullable<int> FK_TypeID { get; set; }
        public Nullable<int> FK_CatID { get; set; }
        public Nullable<decimal> Charges { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual tbl_Category tbl_Category { get; set; }
        public virtual tbl_Type tbl_Type { get; set; }
    }
}
