//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CardDetails
    {
        public int C_ID { get; set; }
        public Nullable<int> FK_GuestID { get; set; }
        public string Card_Type { get; set; }
        public string Card_Number { get; set; }
        public string ExpiryDate { get; set; }
        public string NameOnCard { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual tbl_Guest tbl_Guest { get; set; }
    }
}
