//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_House
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_House()
        {
            this.tbl_BookingBridge = new HashSet<tbl_BookingBridge>();
            this.tbl_Category = new HashSet<tbl_Category>();
            this.tbl_RoomsDetails = new HashSet<tbl_RoomsDetails>();
        }
    
        public int H_ID { get; set; }
        public int FK_UserID { get; set; }
        public string H_Name { get; set; }
        public string H_Location { get; set; }
        public string H_City { get; set; }
        public string H_Address { get; set; }
        public Nullable<int> H_NoOfRoom { get; set; }
        public string H_Image { get; set; }
        public Nullable<bool> H_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BookingBridge> tbl_BookingBridge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Category> tbl_Category { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RoomsDetails> tbl_RoomsDetails { get; set; }
    }
}
